import pool from './configs/db.js';

async function testID() {
  const [rows] = await pool.query('SELECT reference_no FROM issues');
  console.log('All issues:', rows);
  
  const [[{ maxSeq }]] = await pool.query('SELECT COALESCE(MAX(CAST(SUBSTRING(reference_no, 3) AS UNSIGNED)), 0) as maxSeq FROM issues WHERE reference_no LIKE "P-%"');
  console.log('maxSeq:', maxSeq);
  
  const seq = String(maxSeq + 1).padStart(3, '0');
  const nextId = `P-${seq}`;
  console.log('Next ID generated by backend:', nextId);
  
  process.exit(0);
}

testID();
