/**
 * scripts/ensureEventContent.js
 * Ensures all events have 4–8 rich content paragraphs.
 * Adds paragraphs only where they are missing.
 */
import db from '../configs/db.js';

const RICH_CONTENT = {
    'Annual Education Summit 2024': [
        `The Annual Education Summit 2024 was a landmark gathering that brought together over 500 educators, school principals, district officials, parents, and policy advocates to the Community Hall in Thrissur on March 15, 2024. The summit was convened with a singular mission: to assess the state of education in the region, identify systemic gaps, and chart a clear, actionable roadmap for the next academic cycle.`,
        `The inaugural session was presided over by the District Education Officer, who presented a detailed report on student enrollment trends, dropout rates, learning outcomes data from standardized assessments, and teacher-student ratios across government and aided schools in the region. The data revealed a concerning decline in STEM enrollment at the secondary level, prompting calls for dedicated intervention programs.`,
        `Three panel discussions formed the core of the summit's agenda. The first focused on digital education infrastructure — assessing how many schools had functional computer labs, internet connectivity, and teachers trained to use digital tools effectively. The second panel examined the challenges facing first-generation learners and the support mechanisms needed to keep them engaged through higher secondary education.`,
        `The third and most spirited discussion was on curriculum relevance in the age of artificial intelligence and automation. Educators debated the need to introduce computational thinking, financial literacy, environmental science, and entrepreneurship as core components of the school curriculum alongside traditional subjects.`,
        `A major announcement made at the summit was the launch of a new scholarship fund that would support 500 meritorious but economically disadvantaged students annually, covering tuition, books, and transportation. A partnership with 12 private sector companies was also formalized to sponsor computer labs with high-speed internet in 20 rural schools by the end of the year.`,
        `The closing session featured a creative showcase by students from government schools — science models, short films, and cultural performances — which served as a reminder that despite systemic challenges, extraordinary talent thrives when given the right environment. The summit concluded with a collective resolution to make measurable progress before the next annual review.`,
    ],

    'Health Awareness Drive – Palakkad': [
        `The Health Awareness Drive organized in Palakkad on July 22, 2024 was a transformative public health initiative that brought quality healthcare access directly to the doorstep of over 1,200 residents in a single morning. Planned collaboratively by the Health Department, local gram panchayat, and partnering hospitals, the drive was positioned as a proactive response to the increasing burden of non-communicable diseases in urban and semi-urban Kerala.`,
        `Mobile health units were deployed to the Town Square area beginning at 7:00 AM, staffed by a team of 35 doctors, nurses, pharmacists, and health volunteers. Free consultations were offered for general medicine, gynecology, dentistry, and ophthalmology. The response from residents was enthusiastic — queues formed well before the camp began, with people of all age groups arriving hopeful and curious.`,
        `One of the most impactful components was the free screening program for hypertension, diabetes, thyroid disorders, and anemia. A significant proportion of participants — nearly 18% of those screened — were found to have previously undiagnosed elevated blood sugar or blood pressure levels and were immediately counseled and prescribed medication. Many of these individuals had never visited a doctor in the past two years.`,
        `Awareness sessions were conducted in parallel covering topics including balanced nutrition, the dangers of tobacco and alcohol use, maternal and child health, and menstrual hygiene management. These sessions used visual aids, interactive models, and local-language videos to ensure accessibility for participants with limited formal education.`,
        `A pharmaceutical company partnered with the organizers to provide three months of essential medicines free of charge to senior citizens and economically weaker patients identified during consultations. The organizers also facilitated registration of eligible individuals under the Pradhan Mantri Jan Arogya Yojana and state health insurance schemes, ensuring they would continue to receive subsidized care beyond the event.`,
        `The success of the Palakkad Health Awareness Drive has provided a strong model for replication in neighboring local bodies. A follow-up camp is already planned for October 2024, with an expanded scope to include mental health consultations — a service that participants repeatedly requested and that is critically underrepresented in rural healthcare planning.`,
    ],

    'Smart City Infrastructure Workshop': [
        `The Smart City Infrastructure Workshop organized at the Municipal Auditorium in Thrissur on January 10, 2025 was a forward-looking event that brought technology planners, civic engineers, urban designers, local administrators, and civil society representatives together to explore how digital innovation can transform the physical and service infrastructure of Thrissur city.`,
        `The workshop coincided with the city's selection for the second phase of the Smart Cities Mission and sought to galvanize stakeholder alignment around a shared vision. The keynote address delivered by a senior official from the Ministry of Housing and Urban Affairs outlined the government's expectations from smart city projects — moving beyond surface-level digitization toward systemic change in urban governance and service delivery.`,
        `Technical sessions covered the deployment of Internet of Things (IoT) devices for smart traffic management, waste collection monitoring, and street lighting automation. Participants saw live demonstrations of traffic sensors that adjust signal timings based on real-time vehicle counts, and smart bins equipped with fill-level indicators that optimize garbage collection routes — cutting operational costs by up to 40% in pilot cities.`,
        `A dedicated session on the Integrated Command and Control Centre (ICCC) explained how all city systems could be monitored and managed from a single dashboard, enabling faster emergency response, predictive maintenance of public infrastructure, and real-time grievance tracking. The Thrissur Municipal Corporation announced plans to operationalize its ICCC within 18 months.`,
        `Urban mobility was another key theme, with presentations on non-motorized transport infrastructure — cycle tracks, pedestrian-friendly footpaths, and solar-powered e-rickshaw charging stations. Planners from a successful smart city project in Pune shared implementation lessons, including the importance of phased rollouts and community feedback integration.`,
        `The afternoon concluded with an open feedback session where citizens submitted priority concerns: flooding in low-lying areas, poor street lighting in outer wards, and inefficient hand-pump maintenance. These inputs were documented and will be incorporated into the city's Smart City Project Proposal to be submitted within 30 days of the workshop.`,
    ],

    'Women Empowerment Seminar': [
        `The Women Empowerment Seminar held on March 8, 2025 at the District Community Center was a tribute to the resilience, capability, and leadership of women across the region. Held on International Women's Day, the event brought together over 350 women from diverse backgrounds — homemakers, entrepreneurs, students, healthcare workers, artists, and civic leaders — for a day-long program of inspiration, skill building, and collective celebration.`,
        `The programme began with an address from the District Women and Child Development Officer who highlighted the progress made in women's empowerment indicators in Kerala while acknowledging the persistent gender gaps in workplace participation, entrepreneurship, and political representation. She urged the audience to not just celebrate achievements but to identify the structural barriers that continue to hold women back.`,
        `Three parallel skill workshops were conducted throughout the day. The first focused on digital financial literacy — teaching participants to use UPI platforms, manage household budgets through apps, understand bank products, and identify online scams. The second workshop covered public speaking, negotiation, and professional communication — skills that participants said they rarely had a formal space to develop.`,
        `The third workshop — the most popular of the day — focused on starting a small business from home: product ideation, sourcing, pricing, social media marketing, and accessing microloans from government and cooperative schemes. Fifteen women signed up on the spot for a follow-up three-month incubation program that would provide hands-on mentorship.`,
        `A panel titled "Women Who Changed the Narrative" featured four inspiring speakers — a woman sarpanch from a neighboring panchayat, a former domestic violence survivor turned legal aid worker, a woman farmer who had transformed her family's income through organic cultivation, and a 22-year-old tech startup founder. Their stories were met with a standing ovation that lingered long after the panel concluded.`,
        `The event also included a self-defense demonstration by a certified women's safety trainer, and distribution of self-care hygiene kits funded by a local NGO. A dedicated section for art and craft exhibited creations by women artisans from SHGs, with all pieces available for purchase — generating over ₹40,000 in direct income for the artisan members. The day ended with a pledge of mutual support and solidarity among all attendees.`,
    ],

    'Community Tree Plantation Drive': [
        `The Community Tree Plantation Drive organized on June 5, 2025 — World Environment Day — at Riverside Park, Thrissur brought together over 200 enthusiastic volunteers from schools, colleges, resident welfare associations, government offices, and environmental NGOs in a united effort to restore urban green cover and contribute to Kerala's green mission goals.`,
        `The event was inaugurated by the Ward Councilor and the Deputy Forest Officer, who together planted the first sapling — a native Peepal tree — symbolizing the ancient relationship between communities and trees. The officers reminded participants that each tree planted is a gift not to the present but to future generations who will breathe cleaner air, enjoy cooler summers, and live alongside richer biodiversity.`,
        `The plantation was carefully planned to maximize ecological impact. The Forestry Department had pre-selected 1,000 native species suited to the riverside microclimate: Mahogany, Neem, Jackfruit, Tamarind, Indian Kino, and various flowering species that also support pollinator populations. Volunteers were briefed on correct planting techniques — spacing, pit depth, soil preparation, and the importance of watering during the first monsoon season.`,
        `Student teams from three local schools took responsibility for specific plantation zones along the riverside and are now assigned as "Tree Guardians" — a year-long stewardship role where they track the growth and health of their 50-sapling zones and report progress monthly. This educational component was particularly appreciated by teachers and parents as a practical supplement to environmental science education.`,
        `Alongside the planting, an awareness session on climate change and the role of urban forests was conducted. Participants learned about the cooling effect of trees in urban heat islands, how trees capture carbon dioxide and produce oxygen, and how root systems prevent soil erosion and improve groundwater recharge. QR-coded tree tags were attached to each sapling linking to its care instructions and growth tracking page.`,
        `The drive concluded with an Earth pledge signed by all participants, committing to plant at least two saplings personally in the next six months and to discourage activities that damage trees in the neighborhood. The event was widely covered by regional media, inspiring three neighboring wards to plan similar drives in the coming weeks.`,
    ],

    'Youth Leadership Conference 2025': [
        `The Youth Leadership Conference 2025, held at Town Hall in Palakkad on September 20, 2025, was a high-energy, intellectually stimulating event that brought together young leaders from 15 local bodies across the district. Over 400 participants aged 18 to 30 came together for a full-day program designed to challenge conventional thinking, inspire civic action, and build the leadership capacity of the next generation.`,
        `The conference opened with a thought-provoking keynote by a social entrepreneur from Kerala who had built a sustainable livelihood program for tribal youth in the Wayanad hills. He spoke candidly about the obstacles he had faced — skepticism from institutions, lack of initial funding, and social resistance — and how persistence, collaboration, and a clear purpose had enabled him to build something meaningful against the odds.`,
        `Team challenges served as the primary learning vehicle throughout the morning. Groups of 10 were given real-world civic scenarios — managing a flood relief operation, resolving a community conflict over a public space, or designing a youth center on a constrained budget. The challenges required critical thinking, compromise, communication, and decision-making under pressure — skills that formal education rarely develops explicitly.`,
        `Expert-led sessions covered a range of leadership competencies: emotional intelligence in public life, non-violent communication for conflict resolution, creating inclusive organizations, and using social media responsibly for positive advocacy. A session by a feminist activist on gender-sensitive leadership drew particular engagement, with many male participants reflecting openly on blind spots in their own organizations.`,
        `Young leaders were given a platform to present their community initiatives — from hyper-local waste management projects to coding clubs for underprivileged children. A competition recognized the three most impactful and feasible projects, awarding seed funding of ₹25,000 each. These awards were celebrated not just as individual achievements but as demonstration that youth-led change is both possible and fundable.`,
        `The conference concluded with the formation of the District Youth Leaders' Network — a peer accountability group that will meet quarterly, share resources, support each other's projects, and collectively advocate for youth-inclusive governance. Participants left with both inspiration and concrete tools, having also exchanged contact information and formed teams to collaborate beyond the event.`,
        `The Youth Leadership Conference 2025 has already created ripples across the district. Three local bodies have invited conference alumni to advise on youth development policies, and two schools have requested that the conference team design a leadership curriculum for senior students. It is a reminder that when young people are trusted with responsibility, they rise to meet it in ways that can transform entire communities.`,
    ],

    'Digital Literacy Workshop 2026': [
        `The Digital Literacy Workshop held in January 2026 at the Public Library in Thrissur was a carefully designed programme targeting two often-underserved groups in the digital revolution: senior citizens aged above 60 and homemakers who had never received formal training in using digital tools. The workshop was part of the municipality's broader initiative to ensure that the benefits of digitalization are not restricted to the technically-savvy urban youth.`,
        `The session was planned across four carefully sequenced modules over five hours. The first module introduced participants to smartphones and basic navigation — turning on mobile data, making calls, sending messages, and connecting to Wi-Fi. For many of the 60+ participants, this was the first time they had held a tablet and explored its features with patient guidance, making the experience both exciting and deeply meaningful.`,
        `The second module focused on the essentials of online communication: sending emails, using WhatsApp for family and community groups, and safely sharing documents and photos. A recurring theme in participant questions was concern about safety — how to avoid fraud, identify suspicious messages, and protect personal financial information. Facilitators addressed these concerns in depth, using real examples of WhatsApp scams and phishing attempts.`,
        `The third module focused on accessing government services online: checking property tax payments through the municipality portal, downloading vaccination and health records, applying for pension schemes, and tracking delivery of government benefits. Many participants had been making repeated physical visits to government offices for services that could be resolved online in under five minutes — a realization that sparked both relief and a degree of frustration at the time wasted previously.`,
        `The fourth and final module introduced participants to digital payments through UPI, BHIM, and net banking basics. Step-by-step practice sessions with small amounts allowed participants to experience the transaction flow safely. Financial experts on hand clarified norms around safe PIN usage, transaction limits, and what to do when a transaction fails or results in an unauthorized deduction.`,
        `Each participant received a printed "Digital Handbook" in Malayalam covering key steps from each module, helpline numbers, and a glossary of digital terms in simple language. A follow-up WhatsApp group was created to support continued learning and allow participants to ask questions. Within the first week, over 40 participants had attempted at least one government service transaction online without any assistance — a sign that the workshop had achieved its core goal.`,
    ],

    'Health Screening Camp – Thrissur': [
        `The Health Screening Camp organized at the Ward 7 School Ground in Thrissur on March 1, 2026 was an expression of the municipality's commitment to preventive healthcare — reaching people where they live rather than waiting for them to seek medical help only when crises arise. The camp was a collaborative effort between the Primary Health Centre, a district hospital, two NGOs, and a pharmaceutical company that provided medicines and testing kits.`,
        `The camp operated from 8:00 AM to 1:00 PM and attracted over 550 residents from the ward and neighboring areas. Three main screening stations were set up: one for cardiovascular health (blood pressure, ECG, cholesterol), one for metabolic health (blood sugar, HbA1c, BMI), and one for sensory health (eye acuity, hearing, and dental checks). Each station was staffed by qualified professionals and had a short waiting time due to smooth crowd management.`,
        `The results were sobering in their significance. Nearly 22% of participants were found to have borderline or elevated blood pressure requiring medical follow-up. 14% showed fasting blood sugar above normal thresholds. Ophthalmologists identified refractive errors in 80 participants, many of whom had been experiencing vision difficulties for months without seeking help. Forty patients were immediately referred to the district hospital for further investigation.`,
        `A dedicated section for women's health included breast examination awareness sessions, anemia screening, and family planning consultations conducted by female healthcare workers in a private space to encourage participation and openness. Youth were screened for posture-related issues associated with extended screen time, and guidance was given on ergonomics and physical activity.`,
        `Mental health was given an intentional and visible space at the camp — something rarely seen in community health events. Licensed counselors were available for one-on-one 15-minute sessions in a designated private corner, and a group awareness session was held on recognizing signs of depression, anxiety, and caregiver burnout. The session was attended by over 60 people, with several requesting follow-up appointments.`,
        `The camp demonstrated beyond doubt that when healthcare is made accessible, affordable, and welcoming, people engage with it gratefully. Organizers have proposed making this a quarterly event, with rotating focus areas based on seasonal health risks and community needs.`,
    ],

    'Sector Development Review Meeting': [
        `The Sector Development Review Meeting convened at the Conference Room of the Municipality Office on April 10, 2026 was a structured, data-driven quarterly gathering that brought together heads of all development departments, elected ward representatives, local body officials, and subject matter experts to assess progress on sector-specific development goals set at the beginning of the financial year.`,
        `The meeting opened with a presentation by the Municipal Commissioner who walked participants through a progress dashboard covering key performance indicators for each sector: education enrollment and infrastructure completion rates, healthcare facility utilization, road construction and repair percentages, water supply project timelines, waste management efficiency metrics, and housing scheme disbursement numbers.`,
        `Sector heads were given 20 minutes each to present their quarter's performance, outline challenges faced, and propose resource reallocations or deadline revisions where necessary. The Education Sector Head highlighted delays in constructing toilets in three government schools due to contractor procurement issues — a gap immediately flagged for expedited resolution. The Health Sector reported exceeding its primary care visit targets by 30% but identified a critical infrastructure gap in cold-chain storage for vaccines in rural sub-centers.`,
        `An open review panel composed of two citizen representatives and a retired IAS officer critically examined each presentation, asking pointed questions about accountability gaps and the gap between budget allocation and actual expenditure. The exercise surfaced several instances of under-utilization of funds due to delayed tender processes, prompting a directive to implement e-tendering for all projects above ₹5 lakhs.`,
        `Special recognition was given to the Solid Waste Management Division for achieving 94% households covered under door-to-door collection — a significant improvement from 71% a year ago. Their successful deployment of GPS-tracked collection vehicles and a digital grievance app was cited as a model for other departments to study and replicate.`,
        `The meeting concluded with a commitment architecture: each department documented its revised quarterly targets, resource needs, and interdependence on other departments. A shared digital workspace was created for inter-departmental coordination. The next review meeting was scheduled for July 10, 2026 with a mandate to show measurable progress on all flagged issues.`,
    ],

    'Annual Cultural Festival': [
        `The Annual Cultural Festival scheduled for May 20, 2026 at the Community Open Stage in Palakkad is one of the most eagerly anticipated events in the local calendar — a vibrant, exuberant celebration of the music, dance, food, art, and storytelling traditions that define the cultural identity of this region. In its seventh year, the festival has grown from a modest neighbourhood event into a cultural institution that draws visitors from across the district.`,
        `The festival begins as the sun sets, transforming the open-air stage into a glowing spectacle of lights, colors, and sounds. Folk art forms that are rapidly disappearing from public life — Theyam, Oppana, Margam Kali, Padayani, Kolkali, and Duffmuttu — are given pride of place in the evening's programme, performed by traditional artistes who travel from different parts of Kerala to participate.`,
        `The food village is a festival within the festival — rows of stalls offering traditional recipes that rarely appear in restaurant menus: Palakkadan biriyani, unnakkai, thenga choru, achappam, pazham pori, ela sadya served on fresh banana leaves, and region-specific snacks that trigger waves of nostalgia among older visitors. A dedicated "Heritage Food Court" features dishes prepared by grandmothers from the local communities, each with a story placard about the recipe's cultural origins.`,
        `Young artists are prominently featured — a deliberate policy by the organizing committee to ensure cultural continuity. A youth stage provides an unfiltered platform for emerging musicians, poets, stand-up comedians, and experimental theater groups. This year, a new art installation section has been added where visual artists will create large-scale works over the course of the evening, with the finished pieces auctioned to raise funds for local education programs.`,
        `Craft stalls showcase handloom textiles, terracotta ware, bamboo furniture, hand-painted tiles, and traditional jewelry made by artisan communities. A dedicated space for children features storytelling sessions, puppetry shows, and a hands-on craft corner where kids can make their own clay figurines and fabric prints under guided instruction.`,
        `The night closes with a grand finale — a multi-act musical concert featuring local legends of classical Carnatic music alongside popular folk and fusion artists whose work bridges tradition and contemporary culture. The lighting, sound, and stage design are handled by students from the Fine Arts College as part of their applied learning curriculum. The festival ends past midnight, leaving behind memories, conversations, and a renewed pride in the cultural richness that this community carries.`,
        `Beyond the spectacle, the Annual Cultural Festival serves a deeper social function. It is a gathering point for a community that increasingly lives fragmented across different spaces and schedules. For one evening, age, occupation, and economic background become secondary to a shared experience of beauty, belonging, and joy. The organizing committee is already planning next year's edition with an expanded international cultural exchange segment.`,
    ],

    'Road Safety Awareness Campaign': [
        `The Road Safety Awareness Campaign held on January 20, 2024 along the NH 544 Bypass near Thrissur was a high-visibility public initiative aimed at reducing road accidents in one of the district's most accident-prone arterial roads. Organized jointly by the Regional Transport Office, Traffic Police, and civic volunteers, the campaign combined education, enforcement, and community engagement in a half-day programme that reached over 800 commuters.`,
        `The stretch of the NH 544 bypass in Thrissur had seen a troubling 35% increase in accident incidents in 2023 compared to the previous year, with speeding, mobile phone use while driving, and failure to wear helmets identified as primary causes in police reports. The campaign was a direct response to these data points, designed to shift both behavior and attitude among regular commuters.`,
        `Volunteers set up checkpoints at three locations along the stretch where vehicles were temporarily halted. Traffic police personnel spoke directly with drivers, cyclists, and two-wheeler riders about specific violations observed. A breath analyzer test was conducted for drivers showing signs of impairment, and over 45 challans were issued for mobile phone use, triple riding, and non-use of helmets.`,
        `While enforcement was one component, the organizers were deliberate about not letting it overshadow the educational intent. Street plays performed by a youth drama group from a local college portrayed accident scenarios and their aftermath with emotional realism, drawing gasps and applause from the assembled crowd. Survivors of road accidents spoke about their experiences, and a doctor from a trauma care center explained the difference between injuries that are survivable with a helmet versus those that are fatal without one.`,
        `Schools participated meaningfully in the campaign — students from three nearby schools had submitted drawings, essays, and videos on road safety as part of a week-long competition. The winning entries were displayed at the event, and top contestants were felicitated with shields and cash prizes. The process of researching and creating these entries had already seeded important road safety knowledge among the students and, through them, in their families.`,
        `The campaign concluded with a pledge drive where motorists and pedestrians signed a large banner committing to specific road safety behaviours. The Motor Vehicles Department announced that additional road signage, reflective road markers, and speed monitoring cameras would be installed on the bypass within 90 days. Road safety, as the organizers reminded everyone, is not the responsibility of traffic police alone — it is a shared commitment from every person who uses public roads.`,
    ],

    'Farmers\' Market & Agri Expo 2024': [
        `The Farmers' Market and Agricultural Exposition 2024, held at the District Agricultural Office in Palakkad on April 14, 2024, was a two-day convergence of agriculture, innovation, commerce, and community. For the farmers who participated, it was one of the rare occasions when their expertise was centerstage — not as a social welfare narrative, but as a story of skill, entrepreneurship, and quiet resilience.`,
        `The expo spanned an area of approximately three acres and included over 80 stalls organized across five themed zones: organic produce, horticulture and floriculture, farming technology, cooperative products, and a special women farmers' pavilion. The layout was designed to facilitate easy navigation for both buyers and visitors, ensuring that every participating farmer received adequate exposure to the 2,000+ visitors who attended over the two days.`,
        `Live demonstrations were among the most popular features of the expo. Drip irrigation system setup drew farmer clusters who peppered the demonstrators with practical questions. A drone spraying demonstration by an agri-tech startup caused genuine excitement, with several farmers immediately asking about rental and purchase options. Soil health management and bio-fertilizer preparation sessions were attended by standing audiences throughout both days.`,
        `A critical component of the expo's success was the direct buyer-seller interface programme — a first for this region. Procurement officers from three supermarket chains, two processing units, and an online organic grocery platform were introduced to farmer producers under a facilitated matchmaking format. By the end of day two, letters of intent for recurring procurement contracts had been signed between 18 farmers and buyer organizations, representing an estimated annual income increase of ₹1.5 lakh per farmer.`,
        `The Women Farmers' Pavilion was a source of immense pride. Eighteen women's self-help groups displayed their produce, processed foods, and value-added products — including turmeric powder, banana chips, pickle varieties, and dried fruits. They received not only strong footfall but active purchases, with one SHG selling out their entire stock by the end of day one. The collective received the "Best Innovation Award" at the expo's closing ceremony.`,
        `Agricultural scientists from the Kerala Agricultural University set up a stall where farmers could submit soil samples and receive customized crop management advice. A legal aid desk staffed by a lawyer familiar with agrarian issues helped farmers understand land records, crop insurance claim procedures, and cooperative membership rights. The holistic design of the expo — combining market access, technology, legal support, and recognition — made it a genuinely comprehensive event for the farming community.`,
        `The expo organizers announced that based on its success, the Farmers' Market would be made a quarterly event with rotating host locations across the district. A digital marketplace platform to connect Palakkad farmers with urban buyers year-round was confirmed to be in development. The event was a reminder that when farmers are treated as the professionals and innovators they truly are, the results are transformative.`,
    ],

    'Senior Citizens\' Wellness Day': [
        `The Senior Citizens' Wellness Day organized at the Ward Community Hall in Thrissur on June 1, 2024 was a warmly received initiative that placed the wellbeing, dignity, and joy of the elder community at the absolute center of a day's programming. With an aging population and the increasing prevalence of social isolation, chronic disease, and inadequate care support among seniors, the event was both timely and necessary.`,
        `At the heart of the wellness day was a free medical camp staffed by doctors from general medicine, ophthalmology, orthopedics, and mental health. Over 250 senior citizens were screened, with practitioners taking extra time with each patient — a contrast to the rushed consultations elderly patients often experience in formal healthcare settings. Blood tests were collected and results made available within two hours on-site.`,
        `A gentle yoga and stretching session started the morning, designed specifically for older bodies by a certified senior fitness instructor. The session focused on breath control, joint mobility, balance exercises, and techniques to manage lower back pain — conditions that affect a high percentage of Kerala's elderly population. Participants who had "never done yoga" in their lives left the session asking when the next one would be held.`,
        `A well-being panel discussion moderated by a gerontologist covered cognitive health in aging, managing memory changes, the role of social connection in longevity, and how to navigate grief and loss meaningfully. The frankness and depth of this session clearly addressed a hunger among participants for honest conversations about the realities of aging.`,
        `The cultural programme in the afternoon honored the wisdom and talent of older community members. Senior citizens performed classical songs, Thiruvathira dance, and recited poetry — a celebration of the cultural knowledge they carry. A treasure chest of memories segment where elders shared photographs, stories, and objects from their younger years drew tears, laughter, and generations of family members who had accompanied them.`,
        `Practical support was simultaneously offered: volunteers assisted seniors in enrolling for digital services on their phones, helped them check the status of their pension applications, and connected them with government home care services. A list of local volunteers willing to assist seniors with weekly errands, medication reminders, and hospital accompaniment was compiled and shared. The Wellness Day reinforced the community's commitment to ensuring that growing old is experienced with grace, connection, and care.`,
    ],

    'Water Conservation Workshop': [
        `The Water Conservation Workshop conducted at the Municipal Office Conference Hall on September 10, 2024 was an urgent call to action for the community as groundwater tables across the district continued their alarming decline. Bringing together hydrologists, civil engineers, homemakers, apartment residents, farmers, and local officials, the workshop was an exercise in both awareness and action planning for a resource that many take for granted until it disappears.`,
        `The District Groundwater Officer delivered a stark opening presentation showing maps of the water table depth across different zones of the region, compared across 2005, 2015, and 2024. The visual trend was unmistakable — in 19 years, average groundwater levels had dropped by 8 to 14 meters in the most affected zones. Simultaneously, peak summer demand had increased by 60% due to population growth and changing consumption patterns.`,
        `Expert sessions addressed both the causes and solutions. Unplanned construction that covers natural percolation catchments, the replacement of open wells with borewells, excessive hardscaping of compound surfaces — all were identified as key contributors to the groundwater crisis. Sustainable practices including recharge pits, percolation trenches, rooftop rainwater collection systems, and restoration of traditional ponds were explained through detailed diagrams and working models.`,
        `A technology partner demonstrated a low-cost recharge pit kit that can be installed in a standard household compound in under two hours by a local plumber at a cost of ₹3,500 to ₹8,000 depending on scale. Government subsidy forms covering up to 60% of the installation cost were distributed to all participants, along with step-by-step application guides. The organizers had pre-arranged a list of trained local plumbers willing to install these systems at regulated rates.`,
        `Participants split into ward-level groups to identify specific locations in their neighborhoods where percolation capacity could be improved — open spaces, roadside strips, school grounds, and public parks. Each group produced a simple map-based plan identifying three to five actionable water conservation points within walking distance of their ward. These plans were collected and submitted to the local body for integration into the ward-level development plan.`,
        `The workshop also covered water audit practices — how families and apartment complexes can measure their daily consumption and identify sources of waste. Simple behavioral changes like fixing leaking taps, using washing machine water for floor cleaning, and reducing shower time were quantified in terms of litres saved per month, making the abstract concept of conservation very concrete and personally motivating.`,
        `Before the session concluded, a commitment was made by the local body to restore a historical pond that had been encroached upon and dried up over the past decade. The project, which will restore the pond and create a community greenspace around it, was announced as a joint-funded initiative. The workshop ended not with despair at the scale of the challenge, but with a palpable sense that meaningful action is within the community's grasp if taken collectively.`,
    ],

    'MSME Development Seminar': [
        `The MSME Development Seminar held on November 15, 2024 at the Business Facilitation Centre in Palakkad was designed as a practical, hands-on support event for the thousands of small business operators whose enterprises form the backbone of the local economy but who often remain outside the reach of formal business development services. The daylong event attracted 220 participants — an eclectic mix of first-generation entrepreneurs, established traders, SHG product sellers, artisans, and those still contemplating starting their first venture.`,
        `The economic context framing the seminar was significant. Kerala has one of the highest densities of MSMEs per capita in India, yet also one of the highest MSME attrition rates — businesses failing within the first three years due to thin margins, lack of market access, financing gaps, and limited managerial capacity. The seminar was positioned explicitly as an intervention to address these four barriers.`,
        `A session on access to finance drew the largest crowd. Bankers from four institutions walked through specific loan products — Mudra loans, CGTMSE-backed credit, the Kerala Government's KSWIFT scheme, and KFC's enterprise funding programme. Participants learned how to prepare a bankable business plan, what documentation is required for loan approval, and how to build a credit history if they currently have none. A loan mela component allowed participants to submit loan applications on the spot with bank representatives present to clarify and process them.`,
        `Digital commerce was another major theme. In a hands-on session, participants registered on Meesho, Amazon, and the ONDC network under guidance, photographed their products using just a smartphone, and created their first product listings. An e-commerce mentor who had built a ₹30 lakh annual revenue business from a Palakkad home kitchen shared her journey candidly — including the failures, the algorithm changes that hurt sales, and what ultimately worked.`,
        `A one-hour compliance clinic answered the most common regulatory questions: GST threshold, return filing for micro businesses, food safety licensing requirements, professional tax obligations, and trademark registration. A legal consultant clarified these areas in plain Malayalam, distinguishing between compliance that is truly mandatory and compliance that is often mistakenly assumed to be required.`,
        `The mentorship networking session in the late afternoon was quietly the most high-impact segment of the day. Established business owners from the district were paired with newer entrepreneurs in 20-minute structured conversations facilitated by a trained moderator. Follow-up connections were encouraged, and many pairs exchanged numbers planning to continue their conversations the following week.`,
        `The seminar was evaluated by participants as the most practically useful government-organized business event they had experienced in years — a sentiment captured in written feedback forms. Organizers confirmed that a follow-up full-year mentorship programme would launch in January 2025 with 30 selected participants receiving monthly group coaching, quarterly reviews, and access to a shared resource network.`,
    ],

    'Anti-Drug Awareness Drive': [
        `The Anti-Drug Awareness Drive conducted on February 26, 2025 at the Government Higher Secondary School in Thrissur was a deeply purposeful event that brought together students, parents, teachers, police, psychologists, and reformed drug users in a shared effort to build community resilience against substance abuse. The event was particularly significant given the recent increase in cannabis and synthetic drug cases involving minors in the district.`,
        `The programme opened with a documentary film that followed three young people from different socioeconomic backgrounds through their journeys into drug dependency and eventual recovery. The film was met with near-absolute silence — a powerful indicator of its impact on the 600+ students and family members watching. Several parents were visibly moved, later sharing their concerns about their own children's vulnerability in private conversations with counselors.`,
        `A clinical psychologist then delivered a scientific explanation of addiction — how it rewires the brain's reward system, why casual use can escalate so rapidly for certain individuals, and why willpower alone is rarely sufficient to overcome dependence once it is established. This session effectively dismantled the myth that addiction is a moral failing, creating space for a more compassionate and accurate understanding that is essential for families seeking to support a loved one through recovery.`,
        `Police officials from the Anti-Narcotics Cell presented real case data — anonymized but local — showing the age profiles of those caught with substances, the typical supply chains from dealers to minors, and the specific platforms and methods used to recruit young users. They explained that WhatsApp, Instagram DMs, and online gaming communities have become primary vectors for drug introduction among youth, giving parents and students specific warning signs to watch for.`,
        `A recovered drug user who is now a certified rehabilitation counselor spoke for 30 minutes about his personal journey — how it began with peer pressure at a social event at age 16, the spiral that followed, the impact on his family, and how professional help and community support enabled his recovery. His willingness to share his story publicly was received with evident respect and gratitude, particularly from the student audience.`,
        `The second half of the day featured smaller group workshops. Students in groups of 25 practiced refusal skills — how to decline drug offers in different social scenarios without feeling humiliated or ostracized. Psychodrama techniques were used to make the practice vivid and applicable to real situations. In the parent session, family communication strategies were discussed, including how to create an environment where children feel safe disclosing vulnerable situations.`,
        `The drive concluded with the unveiling of a student-created mural on the school's front wall depicting life, hope, and community strength — a visual commitment to a drug-free campus. The school announced the creation of an Anti-Substance Peer Support Group, with trained student leaders able to provide support and connect peers to professional help through a confidential school referral system.`,
    ],

    'Plastic-Free Ward Initiative Launch': [
        `The launch of the Plastic-Free Ward Initiative on April 22, 2025 — World Earth Day — in the market area of Ward 12, Thrissur was a milestone in the ward's environmental journey. What began as a resolution by the Ward Council six months earlier had transformed through sustained planning and community consultation into a credible, enforceable, and community-owned initiative with genuine momentum behind it.`,
        `Preparatory work before launch day was as important as the launch event itself. Ward volunteers had spent three weekends conducting surveys of all shops and food stalls to understand plastic usage patterns, identify alternatives in use, and gauge shopkeeper willingness to transition. Seventy-two percent of shop owners surveyed said they were supportive of the initiative in principle but needed practical support — affordable alternatives, clear timelines, and a grace period. These inputs shaped the final rollout plan.`,
        `The morning clean-up drive mobilized 170 volunteers who fanned across the market streets, adjacent lanes, and the nearby canal bank. They collected, sorted, and weighed 420 kilograms of plastic waste in three hours. The sorted plastic was handed to the district's Material Recovery Facility for recycling. A separate pile of "problem waste" — multi-layered packaging, flexible plastics that have no recycling pathway — was documented and handed to the municipal waste processor for incineration at a safe temperature.`,
        `Shop owners were given a "Plastic-Free Starter Kit" — 100 jute carry bags branded with the ward's logo, a supplier list for eco-packaging alternatives at wholesale prices, and a timeline document outlining when different categories of prohibited plastics would be phased out. The implementation would be staggered: single-use carry bags by May 31, styrofoam containers by June 30, and plastic straws and cutlery by July 31. Violations after these dates would attract a ₹500 per-day fine.`,
        `The Women's Self-Help Groups present at the launch had developed an entire product line in anticipation of the initiative — cloth bags in three sizes, tiffin boxes lined with banana leaf, and paper cones for dry goods. Their products were displayed and available for purchase at the launch event, with pre-orders from 15 shops placed on the day itself. This entrepreneurial dimension — creating local economic opportunity from the transition — was the initiative's most innovative aspect.`,
        `A student art collective had installed large-scale murals depicting life before and after plastic — vivid, provocative, and shareable images that circulated widely on social media in the days after launch. The media coverage brought the initiative to the attention of the district administration, which has since expressed interest in scaling the model to all 52 wards of the municipality using Ward 12's rollout as a documented case study.`,
        `The Plastic-Free Ward Initiative is not a single event but a continuous process of behavior change, regulation, market development, and community accountability. Its success depends on sustained engagement from residents, traders, and administrators alike. Ward 12 has shown that when communities are treated as partners rather than passive recipients of top-down environmental mandates, they bring creativity, ownership, and conviction that no government directive alone can generate.`,
    ],

    'Children\'s Sports & Talent Fest': [
        `The Children's Sports and Talent Festival at the Sports Complex in Palakkad on December 25, 2025 is a celebration that children across the district count down to with the kind of anticipation usually reserved for major holidays. Now in its seventh year, the festival has become a beloved institution — a day when children are centered, celebrated, and given a stage that is entirely their own.`,
        `Preparations begin months before the event. Schools submit team rosters for sports, art, science, and performance categories. The organizing committee — a volunteer-run group of parents, teachers, and youth sports coaches — reviews entries, prepares venue logistics, coordinates judges, and arranges transportation assistance for children from remote areas who might otherwise not be able to attend.`,
        `The sports programme runs from 7 AM with preliminary heats, building toward exciting afternoon finals. This year's events include track athletics, relay, long jump, shot put, kabaddi, football, badminton, and table tennis. A first-ever Adaptive Sports category — designed alongside specialists from a Kerala special needs school — includes wheelchair racing, beanbag throwing, and tandem relay, ensuring that children with physical disabilities have a legitimate, celebrated competition track of their own.`,
        `The Talent Pavilion hosts events in Carnatic vocals, light music, Western instruments, classical and folk dance, poetry recitation, drawing, clay modelling, origami, and science model demonstration. Judges include performing arts professionals, scientists, and educators who provide written feedback to every participant — not just the winners. "Every child deserves to be seen," is the festival's unofficial mantra.`,
        `The Young Innovators competition, introduced this year for the 12–17 age group, has drawn 28 entries. Participants present their ideas — products, apps, social interventions, and environmental solutions — in a five-minute pitch to a panel including an engineer, a social worker, and an entrepreneur. The three winning teams receive mentorship from a local STEM organization and ₹10,000 in seed funding. Past winners have gone on to formally incubate their ideas, with two having generated small income streams within a year.`,
        `Food stalls serving traditional snacks, a reading corner with curated children's books, a photography zone, and a craft market round out the festival atmosphere. Parents, grandparents, siblings, and teachers all find their own reasons to linger beyond the events they came to cheer at. The festival creates a shared memory of community and childhood that participants carry with them long into adulthood.`,
        `The organizing committee has established a tradition of closing with a free community cultural performance featuring local artists, ending as darkness falls — a moment of light, sound, and collective warmth against the December sky. The festival stands as proof that investing in children's joy, confidence, and creativity is not a luxury but a community priority that pays forward in ways that cannot be easily measured but are unmistakably felt.`,
    ],

    'IT Job Fair 2026': [
        `The IT Job Fair 2026, held on February 14, 2026 at the Government Engineering College campus in Thrissur, was a testament to Kerala's growing ambition to become a first-tier destination for technology talent and investment. With 2,500 job seekers registered and 35 companies setting up hiring stalls, it was the district's largest employment event in living memory — and arguably one of the most productive single-day job fairs in the state.`,
        `The fair's origins lay in a recognition that despite Kerala producing a large number of engineering and technology graduates each year, a significant proportion were leaving the state for employment in Bangalore, Hyderabad, Chennai, or abroad. The IT Job Fair was conceived as a platform to collapse the information gap between local employers who struggle to find candidates and local candidates who assume no opportunities exist close to home.`,
        `The inaugurating address by the IT Secretary underscored the state's commitment to making every taluka a technology zone. She cited recent global IT companies that had set up development centers in Thrissur, Kochi, and Kozhikode as proof that the geography and talent pool of Kerala are increasingly attractive for quality-focused organizations seeking skilled engineers outside the saturated and expensive metro markets.`,
        `Hiring stations across the fairground were organized by technology domain: software development, quality assurance, data analytics and machine learning, cloud infrastructure, cybersecurity, embedded systems, and UI/UX design. Each station had both technical assessors conducting initial screening and HR professionals conducting preliminary cultural fit conversations. Multiple companies conducting simultaneous structured interviews created an energy on the fairground that was both competitive and electric.`,
        `For candidates who were not immediately selected, a "Skill Alignment Zone" provided real-time resume review by professional recruiters, along with direct guidance on which certifications or project experiences would strengthen their profile for re-application. A session by a senior hiring manager from a product company on "What Makes a Hire-Ready Engineer" drew over 300 attendees and was subsequently live-streamed.`,
        `A dedicated zone for returning NRI professionals attracted particular interest, with five companies specifically seeking senior engineers and project managers with international experience who wish to return to Kerala. Several companies offered hybrid or fully remote arrangements — a recognition that post-pandemic work norms have fundamentally changed what is possible for talent that was previously drawn away by geography.`,
        `By the event's close, preliminary data indicated that over 380 conditional offer letters had been issued — the highest number ever recorded at a single district-level job fair in Kerala. The Department of Employment plans to publish a comprehensive impact report within 30 days and has confirmed that the IT Job Fair will now become a bi-annual event with the next edition planned for August 2026.`,
    ],

    'Monsoon Preparedness Meeting': [
        `The Monsoon Preparedness Meeting convened on May 30, 2026 at the Panchayat Meeting Hall was the culmination of months of preparatory work by the district administration, disaster management officials, and community representatives in the lead-up to the southwest monsoon season. In a state that remembers vividly the devastation of the 2018 and 2019 floods, this gathering carries weight beyond bureaucratic formality — it is a community's collective act of preparation and resolve.`,
        `The meeting opened with an extended meteorological briefing. The senior meteorologist from the Regional Weather Office presented the 2026 pre-monsoon outlook: above-normal cumulative rainfall was predicted with higher probability of intense spells in June and July. Specific micro-zones within the district with historically poor drainage and topographic vulnerability to flash flooding were mapped and projected for all participants.`,
        `Each department head presented their monsoon readiness status. The Public Works Department reported that 84% of flagged road repairs had been completed, with 16% remaining due to delayed material supplies — these were immediately escalated for priority completion within 10 days. The Irrigation Department confirmed that sluice gates on three major canals had been inspected and found functional. The Water Authority reported that all pumping stations had backup generators tested and operational.`,
        `The relief camp identification and provisioning review found 23 camps established across the panchayat zone, each stocked with foodgrain for 500 persons for seven days, drinking water reserves, first aid kits, emergency lighting, and rainwear. However, two camps lacked adequate sanitation facilities for women — an issue raised by a female elected representative and addressed with an urgent directive to the sanitation department.`,
        `Community Disaster Response Teams (CDRT) — groups of trained volunteers who can conduct basic search and rescue, first aid, and evacuation before professional forces arrive — were reviewed. Forty-two teams with a total of 420 trained members are operations-ready across the zone. A gap of coverage was identified in three remote hamlets in the hilly border areas, and a rapid training camp for 30 new volunteers from these areas was scheduled for the following weekend.`,
        `Mock drill protocols were finalized for a large-scale simulation exercise to be conducted at a flood-prone ward the following Saturday. The drill will test inter-agency coordination, communication channel reliability, evacuation speed, and public announcement systems. Lessons from the drill will inform last-minute preparations before peak monsoon onset.`,
        `The meeting closed with a message that has become the district's monsoon preparedness mantra: no life is expendable to a preventable disaster. With thorough preparation, coordinated response, and community awareness, the impact of even extreme weather events can be mitigated. Every participant left the meeting with updated contact lists, a clear understanding of their role in the response chain, and a copy of the ward-level emergency action plan.`,
    ],
};

async function run() {
    console.log('📝 Ensuring all events have rich content (4–8 paragraphs)...\n');

    const [events] = await db.query(
        `SELECT e.id, e.event_name, COUNT(ec.id) as cnt
         FROM events e
         LEFT JOIN event_content ec ON ec.event_id = e.id
         GROUP BY e.id
         ORDER BY e.id ASC`
    );

    console.log(`Found ${events.length} total events.\n`);

    let updated = 0;
    let skipped = 0;

    for (const event of events) {
        const content = RICH_CONTENT[event.event_name];

        if (!content) {
            console.log(`  ⏭️  No content template for: "${event.event_name.slice(0, 50)}" — skipping`);
            skipped++;
            continue;
        }

        if (event.cnt >= 4) {
            console.log(`  ✅  "${event.event_name.slice(0, 50)}" already has ${event.cnt} paragraphs — skipping`);
            skipped++;
            continue;
        }

        // Delete any existing short content first
        if (event.cnt > 0) {
            await db.query('DELETE FROM event_content WHERE event_id = ?', [event.id]);
        }

        // Insert full rich content
        for (let i = 0; i < content.length; i++) {
            await db.query(
                'INSERT INTO event_content (event_id, content_order, paragraph_text) VALUES (?, ?, ?)',
                [event.id, i + 1, content[i]]
            );
        }
        console.log(`  ✅  "${event.event_name.slice(0, 50)}" — inserted ${content.length} paragraphs`);
        updated++;
    }

    console.log(`\n🎉 Done! Updated: ${updated} events, Skipped: ${skipped}.`);
    process.exit(0);
}

run().catch(err => {
    console.error('❌ Failed:', err.message);
    process.exit(1);
});
